version: '3.8'
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    healthcheck:
      test: "mysql -u${MYSQLDB_USER} -p${MYSQLDB_ROOT_PASSWORD} ${MYSQLDB_DATABASE} -e 'select 1'"
      interval: 5s
      timeout: 1s
      retries: 120

  backend:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    image: book_store_app
    build: .
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "validate",
        "jwt.secret" : "$JWT_SECRET",
        "age.for.registration" : "$AGE.FOR.REGISTRATION",
        "prefix.for.phone.number" : "$PREFIX.FOR.NUMBER",
        "jwt.expiration" : "$EXPIRATION_TIME"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
